spring.application.name=GrupoEragin

spring.datasource.url=jdbc:postgresql://localhost:5432/eragin_db
spring.datasource.username=eragin_user
spring.datasource.password=eragin_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080